version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: random_adventures
    volumes:
      - db_data:/var/lib/mysql
      # Auto-run schema and seed on first container start
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backend/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=example
      - DB_NAME=random_adventures
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
